name: video_uploader
description: This flutter plugin is an easy way to upload video to api.video.
version: 1.0.0
repository: https://github.com/apivideo/api.video-flutter-uploader
issue_tracker: https://github.com/apivideo/api.video-flutter-uploader/issues
homepage: https://api.video

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  json_annotation: ^4.4.0
  plugin_platform_interface: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^6.1.1

flutter:
  plugin:
    platforms:
      android:
        package: video.api.flutter.uploader
        pluginClass: UploaderPlugin
      ios:
        pluginClass: UploaderPlugin
      web:
        pluginClass: ApiVideoUploaderPlugin
        fileName: src/web/apivideo_uploader_web.dart
