name: Build
on: [ push ]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

  build_ios:
    needs: setup
    runs-on: macos-latest
    defaults:
      run:
        working-directory: example/
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Build iOS application
        run: flutter build ios --no-codesign

  build_android:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Build Android application
        run: flutter build apk

  build_web:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Build Web application
        run: flutter build web

  run_tests:
    needs: [ build_web, build_android, build_ios ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Run tests
        run: flutter test

  analyze_project:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze

  test_publish:
    needs: analyze_project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: test flutter pub publish --dry-run
        run: flutter pub publish --dry-run
